import { Router, type IRouter } from "express";
import { requireAuth } from "../middlewares/auth";
import healthRouter from "./health";
import schoolsRouter from "./schools";
import studentsRouter from "./students";
import staffRouter from "./staff";
import servicesRouter from "./services";
import sessionsRouter from "./sessions";
import schedulesRouter from "./schedules";
import alertsRouter from "./alerts";
import dashboardRouter from "./dashboard";
import minuteProgressRouter from "./minuteProgress";
import reportsRouter from "./reports";
import importsRouter from "./imports";
import programDataRouter from "./programData";
import iepRouter from "./iep";
import complianceTimelineRouter from "./complianceTimeline";
import additionalFeaturesRouter from "./additionalFeatures";
import protectiveMeasuresRouter from "./protectiveMeasures";
import analyticsRouter from "./analytics";
import classesRouter from "./classes";
import assignmentsRouter from "./assignments";
import iepSuggestionsRouter from "./iepSuggestions";
import classroomRouter from "./classroom";
import districtsRouter from "./districts";
import fbaRouter from "./fba";
import iepBuilderRouter from "./iepBuilder";
import resourceManagementRouter from "./resourceManagement";
import compensatoryRouter from "./compensatory";
import parentCommunicationRouter from "./parentCommunication";
import supervisionRouter from "./supervision";
import paraRouter from "./para";
import auditLogRouter from "./auditLog";

const router: IRouter = Router();

router.use(healthRouter);

router.use(requireAuth);

router.use(schoolsRouter);
router.use(districtsRouter);
router.use(studentsRouter);
router.use(staffRouter);
router.use(servicesRouter);
router.use(sessionsRouter);
router.use(schedulesRouter);
router.use(alertsRouter);
router.use(dashboardRouter);
router.use(minuteProgressRouter);
router.use(reportsRouter);
router.use(importsRouter);
router.use(programDataRouter);
router.use(iepRouter);
router.use(complianceTimelineRouter);
router.use(additionalFeaturesRouter);
router.use(protectiveMeasuresRouter);
router.use(analyticsRouter);
router.use(classesRouter);
router.use(assignmentsRouter);
router.use(iepSuggestionsRouter);
router.use(classroomRouter);
router.use(fbaRouter);
router.use(iepBuilderRouter);
router.use(resourceManagementRouter);
router.use(compensatoryRouter);
router.use(parentCommunicationRouter);
router.use(supervisionRouter);
router.use(paraRouter);
router.use(auditLogRouter);

export default router;
