import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  scheduleBlocksTable, staffTable, studentsTable, serviceTypesTable,
  staffAssignmentsTable, serviceRequirementsTable, staffAbsencesTable,
  coverageInstancesTable
} from "@workspace/db";
import {
  ListScheduleBlocksQueryParams,
  CreateScheduleBlockBody,
  UpdateScheduleBlockParams,
  UpdateScheduleBlockBody,
  DeleteScheduleBlockParams,
  GetScheduleConflictsQueryParams,
  GenerateScheduleBody,
  AcceptGeneratedScheduleBody,
  ListStaffAssignmentsQueryParams,
  CreateStaffAssignmentBody,
  DeleteStaffAssignmentParams,
  AssignSubstituteParams,
  AssignSubstituteBody,
  ListUncoveredSessionsQueryParams,
} from "@workspace/api-zod";
import { eq, and, sql, isNull } from "drizzle-orm";
import { requireRoles } from "../middlewares/auth";
import { computeAllActiveMinuteProgress } from "../lib/minuteCalc";
import { getActiveSchoolYearId, getActiveSchoolYearIdForStudent } from "../lib/activeSchoolYear";
import { getPublicMeta } from "../lib/clerkClaims";
import type { Request } from "express";

const requireAdmin = requireRoles("admin", "coordinator");

async function resolveActiveYearId(req: Request, districtIdHint?: number | null): Promise<number | null> {
  const did = districtIdHint ?? getPublicMeta(req).districtId;
  if (did) return getActiveSchoolYearId(did);
  if (process.env.NODE_ENV !== "production") {
    const { pool } = await import("@workspace/db");
    const result = await pool.query<{ id: number }>("SELECT id FROM school_years WHERE is_active = true ORDER BY id LIMIT 1");
    return result.rows[0]?.id ?? null;
  }
  return null;
}

const router: IRouter = Router();

function blockToJson(b: any, staffName?: string | null, studentName?: string | null, serviceTypeName?: string | null) {
  return {
    id: b.id,
    staffId: b.staffId,
    staffName: staffName ?? null,
    studentId: b.studentId,
    studentName: studentName ?? null,
    serviceTypeId: b.serviceTypeId,
    serviceTypeName: serviceTypeName ?? null,
    dayOfWeek: b.dayOfWeek,
    startTime: b.startTime,
    endTime: b.endTime,
    location: b.location,
    blockLabel: b.blockLabel,
    blockType: b.blockType,
    notes: b.notes,
    isRecurring: b.isRecurring,
    recurrenceType: b.recurrenceType ?? "weekly",
    effectiveFrom: b.effectiveFrom ?? null,
    effectiveTo: b.effectiveTo ?? null,
    weekOf: b.weekOf,
    isAutoGenerated: b.isAutoGenerated,
    rotationDay: b.rotationDay ?? null,
    createdAt: b.createdAt instanceof Date ? b.createdAt.toISOString() : b.createdAt,
  };
}

router.get("/schedule-blocks", async (req, res): Promise<void> => {
  const params = ListScheduleBlocksQueryParams.safeParse(req.query);
  const conditions: any[] = [isNull(scheduleBlocksTable.deletedAt)];
  if (params.success) {
    if (params.data.staffId) conditions.push(eq(scheduleBlocksTable.staffId, Number(params.data.staffId)));
    if (params.data.studentId) conditions.push(eq(scheduleBlocksTable.studentId, Number(params.data.studentId)));
    if (params.data.dayOfWeek) conditions.push(eq(scheduleBlocksTable.dayOfWeek, params.data.dayOfWeek));
    if (params.data.weekOf) conditions.push(eq(scheduleBlocksTable.weekOf, params.data.weekOf));
  }
  if (params.success && params.data.schoolId) conditions.push(sql`${scheduleBlocksTable.staffId} IN (SELECT id FROM staff WHERE school_id = ${Number(params.data.schoolId)})`);
  if (params.success && params.data.districtId) conditions.push(sql`${scheduleBlocksTable.staffId} IN (SELECT id FROM staff WHERE school_id IN (SELECT id FROM schools WHERE district_id = ${Number(params.data.districtId)}))`);

  // School year isolation: use explicit schoolYearId if provided, otherwise default to active year
  const explicitYearId = params.success ? (params.data.schoolYearId ?? null) : null;
  const activeYearId = explicitYearId ?? await resolveActiveYearId(req, params.success ? (params.data.districtId ?? null) : null);
  if (activeYearId != null) {
    conditions.push(eq(scheduleBlocksTable.schoolYearId, activeYearId));
  }

  const blocks = await db
    .select({
      id: scheduleBlocksTable.id,
      staffId: scheduleBlocksTable.staffId,
      studentId: scheduleBlocksTable.studentId,
      serviceTypeId: scheduleBlocksTable.serviceTypeId,
      dayOfWeek: scheduleBlocksTable.dayOfWeek,
      startTime: scheduleBlocksTable.startTime,
      endTime: scheduleBlocksTable.endTime,
      location: scheduleBlocksTable.location,
      blockLabel: scheduleBlocksTable.blockLabel,
      blockType: scheduleBlocksTable.blockType,
      notes: scheduleBlocksTable.notes,
      isRecurring: scheduleBlocksTable.isRecurring,
      recurrenceType: scheduleBlocksTable.recurrenceType,
      effectiveFrom: scheduleBlocksTable.effectiveFrom,
      effectiveTo: scheduleBlocksTable.effectiveTo,
      weekOf: scheduleBlocksTable.weekOf,
      isAutoGenerated: scheduleBlocksTable.isAutoGenerated,
      rotationDay: scheduleBlocksTable.rotationDay,
      createdAt: scheduleBlocksTable.createdAt,
      staffFirst: staffTable.firstName,
      staffLast: staffTable.lastName,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
      serviceTypeName: serviceTypesTable.name,
    })
    .from(scheduleBlocksTable)
    .leftJoin(staffTable, eq(staffTable.id, scheduleBlocksTable.staffId))
    .leftJoin(studentsTable, eq(studentsTable.id, scheduleBlocksTable.studentId))
    .leftJoin(serviceTypesTable, eq(serviceTypesTable.id, scheduleBlocksTable.serviceTypeId))
    .where(conditions.length > 0 ? and(...conditions) : undefined);

  res.json(blocks.map(b => blockToJson(b,
    b.staffFirst ? `${b.staffFirst} ${b.staffLast}` : null,
    b.studentFirst ? `${b.studentFirst} ${b.studentLast}` : null,
    b.serviceTypeName
  )));
});

router.post("/schedule-blocks", async (req, res): Promise<void> => {
  const parsed = CreateScheduleBlockBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const schoolYearId = parsed.data.studentId
    ? await getActiveSchoolYearIdForStudent(parsed.data.studentId)
    : null;
  const [block] = await db.insert(scheduleBlocksTable).values({
    ...parsed.data,
    isAutoGenerated: false,
    ...(schoolYearId != null ? { schoolYearId } : {}),
  }).returning();
  res.status(201).json(blockToJson(block));
});

router.patch("/schedule-blocks/:id", async (req, res): Promise<void> => {
  const params = UpdateScheduleBlockParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }
  const parsed = UpdateScheduleBlockBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const updateData: Partial<typeof scheduleBlocksTable.$inferInsert> = {};
  if (parsed.data.studentId !== undefined) updateData.studentId = parsed.data.studentId;
  if (parsed.data.dayOfWeek != null) updateData.dayOfWeek = parsed.data.dayOfWeek;
  if (parsed.data.startTime != null) updateData.startTime = parsed.data.startTime;
  if (parsed.data.endTime != null) updateData.endTime = parsed.data.endTime;
  if (parsed.data.location !== undefined) updateData.location = parsed.data.location;
  if (parsed.data.blockLabel !== undefined) updateData.blockLabel = parsed.data.blockLabel;
  if (parsed.data.notes !== undefined) updateData.notes = parsed.data.notes;
  if (parsed.data.recurrenceType != null) updateData.recurrenceType = parsed.data.recurrenceType;
  if (parsed.data.effectiveFrom !== undefined) updateData.effectiveFrom = parsed.data.effectiveFrom ?? null;
  if (parsed.data.effectiveTo !== undefined) updateData.effectiveTo = parsed.data.effectiveTo ?? null;

  const [block] = await db.update(scheduleBlocksTable).set(updateData).where(eq(scheduleBlocksTable.id, params.data.id)).returning();
  if (!block) {
    res.status(404).json({ error: "Block not found" });
    return;
  }
  res.json(blockToJson(block));
});

router.delete("/schedule-blocks/:id", async (req, res): Promise<void> => {
  const params = DeleteScheduleBlockParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }
  await db.update(scheduleBlocksTable).set({ deletedAt: new Date() }).where(eq(scheduleBlocksTable.id, params.data.id));
  res.sendStatus(204);
});

// Conflicts detection
router.get("/schedule-blocks/conflicts", async (req, res): Promise<void> => {
  const conflictYearId = await resolveActiveYearId(req, null);
  const conflictConditions: any[] = [eq(scheduleBlocksTable.isRecurring, true), isNull(scheduleBlocksTable.deletedAt)];
  if (conflictYearId != null) conflictConditions.push(eq(scheduleBlocksTable.schoolYearId, conflictYearId));

  const allBlocks = await db
    .select({
      id: scheduleBlocksTable.id,
      staffId: scheduleBlocksTable.staffId,
      dayOfWeek: scheduleBlocksTable.dayOfWeek,
      startTime: scheduleBlocksTable.startTime,
      endTime: scheduleBlocksTable.endTime,
      studentId: scheduleBlocksTable.studentId,
      staffFirst: staffTable.firstName,
      staffLast: staffTable.lastName,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
    })
    .from(scheduleBlocksTable)
    .leftJoin(staffTable, eq(staffTable.id, scheduleBlocksTable.staffId))
    .leftJoin(studentsTable, eq(studentsTable.id, scheduleBlocksTable.studentId))
    .where(and(...conflictConditions));

  // Group by staff + day
  const grouped = new Map<string, typeof allBlocks>();
  for (const b of allBlocks) {
    const key = `${b.staffId}-${b.dayOfWeek}`;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(b);
  }

  const conflicts = [];
  for (const [_, blocks] of grouped.entries()) {
    if (blocks.length < 2) continue;
    const conflictingPairs: any[] = [];
    for (let i = 0; i < blocks.length; i++) {
      for (let j = i + 1; j < blocks.length; j++) {
        const a = blocks[i];
        const b = blocks[j];
        if (a.startTime < b.endTime && b.startTime < a.endTime) {
          // Calculate overlap
          const overlapStart = a.startTime > b.startTime ? a.startTime : b.startTime;
          const overlapEnd = a.endTime < b.endTime ? a.endTime : b.endTime;
          const [osH, osM] = overlapStart.split(":").map(Number);
          const [oeH, oeM] = overlapEnd.split(":").map(Number);
          const overlapMinutes = (oeH * 60 + oeM) - (osH * 60 + osM);

          conflictingPairs.push({
            staffId: a.staffId,
            staffName: a.staffFirst ? `${a.staffFirst} ${a.staffLast}` : `Staff ${a.staffId}`,
            dayOfWeek: a.dayOfWeek,
            conflictingBlocks: [
              { id: a.id, startTime: a.startTime, endTime: a.endTime, studentName: a.studentFirst ? `${a.studentFirst} ${a.studentLast}` : null },
              { id: b.id, startTime: b.startTime, endTime: b.endTime, studentName: b.studentFirst ? `${b.studentFirst} ${b.studentLast}` : null },
            ],
            overlapMinutes,
          });
        }
      }
    }
    conflicts.push(...conflictingPairs);
  }

  res.json(conflicts);
});

// Coverage gaps
router.get("/schedule-blocks/coverage-gaps", async (req, res): Promise<void> => {
  // Find students with active service requirements who have no scheduled blocks in the active year
  const gapYearId = await resolveActiveYearId(req, null);
  const coveredConditions: any[] = [eq(scheduleBlocksTable.isRecurring, true), isNull(scheduleBlocksTable.deletedAt)];
  if (gapYearId != null) coveredConditions.push(eq(scheduleBlocksTable.schoolYearId, gapYearId));

  const reqs = await db
    .select({
      id: serviceRequirementsTable.id,
      studentId: serviceRequirementsTable.studentId,
      serviceTypeId: serviceRequirementsTable.serviceTypeId,
      requiredMinutes: serviceRequirementsTable.requiredMinutes,
      intervalType: serviceRequirementsTable.intervalType,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
      serviceTypeName: serviceTypesTable.name,
    })
    .from(serviceRequirementsTable)
    .leftJoin(studentsTable, eq(studentsTable.id, serviceRequirementsTable.studentId))
    .leftJoin(serviceTypesTable, eq(serviceTypesTable.id, serviceRequirementsTable.serviceTypeId))
    .where(eq(serviceRequirementsTable.active, true));

  const coveredPairs = await db
    .selectDistinct({
      studentId: scheduleBlocksTable.studentId,
      serviceTypeId: scheduleBlocksTable.serviceTypeId,
    })
    .from(scheduleBlocksTable)
    .where(and(...coveredConditions));

  const coveredSet = new Set(coveredPairs.map(p => `${p.studentId}-${p.serviceTypeId}`));

  const gaps = reqs
    .filter(req => !coveredSet.has(`${req.studentId}-${req.serviceTypeId}`))
    .map(req => ({
      studentId: req.studentId,
      studentName: req.studentFirst ? `${req.studentFirst} ${req.studentLast}` : `Student ${req.studentId}`,
      serviceRequirementId: req.id,
      serviceTypeName: req.serviceTypeName ?? "Unknown",
      gapDescription: `No scheduled blocks found for ${req.serviceTypeName ?? "this service"} (${req.requiredMinutes} min/${req.intervalType} required)`,
      severity: req.requiredMinutes > 60 ? "high" : "medium",
    }));

  res.json(gaps);
});

// Auto-scheduler
router.post("/scheduler/generate", async (req, res): Promise<void> => {
  const parsed = GenerateScheduleBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  const { weekOf, staffIds, studentIds } = parsed.data;

  // Get all active service requirements
  const reqConditions: any[] = [eq(serviceRequirementsTable.active, true)];
  if (studentIds && studentIds.length > 0) {
    // Filter to specific students - simplified
  }

  const reqs = await db
    .select({
      id: serviceRequirementsTable.id,
      studentId: serviceRequirementsTable.studentId,
      providerId: serviceRequirementsTable.providerId,
      serviceTypeId: serviceRequirementsTable.serviceTypeId,
      requiredMinutes: serviceRequirementsTable.requiredMinutes,
      intervalType: serviceRequirementsTable.intervalType,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
      serviceTypeName: serviceTypesTable.name,
    })
    .from(serviceRequirementsTable)
    .leftJoin(studentsTable, eq(studentsTable.id, serviceRequirementsTable.studentId))
    .leftJoin(serviceTypesTable, eq(serviceTypesTable.id, serviceRequirementsTable.serviceTypeId))
    .where(eq(serviceRequirementsTable.active, true));

  const allStaff = await db.select().from(staffTable).where(eq(staffTable.status, "active"));

  const days = ["monday", "tuesday", "wednesday", "thursday", "friday"];
  const timeSlots = ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00"];
  const SLOT_DURATION = 60; // minutes

  const proposedBlocks: any[] = [];
  const unresolvedDeficits: any[] = [];

  // Track staff bookings to avoid double-booking
  const staffBookings = new Map<string, string[]>(); // key: staffId-day, value: array of "startTime-endTime"

  function isSlotAvailable(staffId: number, day: string, startTime: string): boolean {
    const key = `${staffId}-${day}`;
    const bookings = staffBookings.get(key) ?? [];
    const slotEnd = addMinutes(startTime, SLOT_DURATION);
    return !bookings.some(b => {
      const [bStart, bEnd] = b.split("-");
      return startTime < bEnd && slotEnd > bStart;
    });
  }

  function bookSlot(staffId: number, day: string, startTime: string) {
    const key = `${staffId}-${day}`;
    if (!staffBookings.has(key)) staffBookings.set(key, []);
    staffBookings.get(key)!.push(`${startTime}-${addMinutes(startTime, SLOT_DURATION)}`);
  }

  function addMinutes(time: string, minutes: number): string {
    const [h, m] = time.split(":").map(Number);
    const total = h * 60 + m + minutes;
    return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`;
  }

  // Simple constraint-based scheduler
  for (const req of reqs) {
    const provider = req.providerId ? allStaff.find(s => s.id === req.providerId) : null;
    if (!provider) {
      unresolvedDeficits.push({
        studentId: req.studentId,
        studentName: req.studentFirst ? `${req.studentFirst} ${req.studentLast}` : `Student ${req.studentId}`,
        serviceRequirementId: req.id,
        serviceTypeName: req.serviceTypeName ?? "Unknown",
        gapDescription: `No provider assigned for ${req.serviceTypeName}`,
        severity: "high",
      });
      continue;
    }

    // Determine sessions needed per week (rough estimate based on interval)
    let sessionsPerWeek = 1;
    if (req.intervalType === "weekly") sessionsPerWeek = Math.ceil(req.requiredMinutes / SLOT_DURATION);
    else if (req.intervalType === "monthly") sessionsPerWeek = Math.ceil(req.requiredMinutes / (SLOT_DURATION * 4));
    else if (req.intervalType === "daily") sessionsPerWeek = 5;

    let scheduled = 0;
    for (const day of days) {
      if (scheduled >= sessionsPerWeek) break;
      for (const time of timeSlots) {
        if (scheduled >= sessionsPerWeek) break;
        if (isSlotAvailable(provider.id, day, time)) {
          bookSlot(provider.id, day, time);
          proposedBlocks.push({
            id: -(proposedBlocks.length + 1), // temp negative id for proposed
            staffId: provider.id,
            staffName: `${provider.firstName} ${provider.lastName}`,
            studentId: req.studentId,
            studentName: req.studentFirst ? `${req.studentFirst} ${req.studentLast}` : null,
            serviceTypeId: req.serviceTypeId,
            serviceTypeName: req.serviceTypeName,
            dayOfWeek: day,
            startTime: time,
            endTime: addMinutes(time, SLOT_DURATION),
            location: null,
            blockLabel: req.serviceTypeName ?? null,
            blockType: "service",
            notes: `Auto-generated for week of ${weekOf}`,
            isRecurring: false,
            weekOf,
            isAutoGenerated: true,
            createdAt: new Date().toISOString(),
          });
          scheduled++;
        }
      }
    }

    if (scheduled < sessionsPerWeek) {
      unresolvedDeficits.push({
        studentId: req.studentId,
        studentName: req.studentFirst ? `${req.studentFirst} ${req.studentLast}` : `Student ${req.studentId}`,
        serviceRequirementId: req.id,
        serviceTypeName: req.serviceTypeName ?? "Unknown",
        gapDescription: `Could only schedule ${scheduled} of ${sessionsPerWeek} sessions for ${req.serviceTypeName}`,
        severity: scheduled === 0 ? "high" : "medium",
      });
    }
  }

  // Compute projected fulfillment
  const projectedFulfillment = await computeAllActiveMinuteProgress();

  res.json({
    weekOf,
    proposedBlocks,
    unresolvedDeficits,
    conflicts: [],
    projectedFulfillment,
    summary: `Generated ${proposedBlocks.length} proposed schedule blocks for week of ${weekOf}. ${unresolvedDeficits.length} unresolved gaps remain.`,
  });
});

router.post("/scheduler/accept", async (req, res): Promise<void> => {
  const parsed = AcceptGeneratedScheduleBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  // In a real system we'd store proposed blocks in a temp table and promote them
  // For now, we just return a success response
  res.json({ acceptedCount: parsed.data.blockIds.length, message: `Accepted ${parsed.data.blockIds.length} schedule blocks for week of ${parsed.data.weekOf}` });
});

// Staff Assignments
router.get("/staff-assignments", async (req, res): Promise<void> => {
  const params = ListStaffAssignmentsQueryParams.safeParse(req.query);
  const conditions: any[] = [];
  if (params.success) {
    if (params.data.staffId) conditions.push(eq(staffAssignmentsTable.staffId, Number(params.data.staffId)));
    if (params.data.studentId) conditions.push(eq(staffAssignmentsTable.studentId, Number(params.data.studentId)));
  }

  const assignments = await db
    .select({
      id: staffAssignmentsTable.id,
      staffId: staffAssignmentsTable.staffId,
      studentId: staffAssignmentsTable.studentId,
      assignmentType: staffAssignmentsTable.assignmentType,
      startDate: staffAssignmentsTable.startDate,
      endDate: staffAssignmentsTable.endDate,
      notes: staffAssignmentsTable.notes,
      createdAt: staffAssignmentsTable.createdAt,
      staffFirst: staffTable.firstName,
      staffLast: staffTable.lastName,
      staffRole: staffTable.role,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
    })
    .from(staffAssignmentsTable)
    .leftJoin(staffTable, eq(staffTable.id, staffAssignmentsTable.staffId))
    .leftJoin(studentsTable, eq(studentsTable.id, staffAssignmentsTable.studentId))
    .where(conditions.length > 0 ? and(...conditions) : undefined);

  res.json(assignments.map(a => ({
    ...a,
    staffName: a.staffFirst ? `${a.staffFirst} ${a.staffLast}` : null,
    staffRole: a.staffRole,
    studentName: a.studentFirst ? `${a.studentFirst} ${a.studentLast}` : null,
    createdAt: a.createdAt.toISOString(),
  })));
});

router.post("/staff-assignments", async (req, res): Promise<void> => {
  const parsed = CreateStaffAssignmentBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const [assignment] = await db.insert(staffAssignmentsTable).values(parsed.data).returning();
  res.status(201).json({ ...assignment, createdAt: assignment.createdAt.toISOString() });
});

router.delete("/staff-assignments/:id", async (req, res): Promise<void> => {
  const params = DeleteStaffAssignmentParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }
  await db.delete(staffAssignmentsTable).where(eq(staffAssignmentsTable.id, params.data.id));
  res.sendStatus(204);
});

// Uncovered sessions — instances from coverage_instances where is_covered = false
router.get("/schedule-blocks/uncovered", requireAdmin, async (req, res): Promise<void> => {
  const params = ListUncoveredSessionsQueryParams.safeParse(req.query);
  const { pool } = await import("@workspace/db");

  const whereClauses = ["ci.is_covered = false", "sb.deleted_at IS NULL"];
  const queryParams: any[] = [];

  if (params.success && params.data.schoolId) {
    queryParams.push(Number(params.data.schoolId));
    whereClauses.push(`sb.staff_id IN (SELECT id FROM staff WHERE school_id = $${queryParams.length})`);
  }
  if (params.success && params.data.startDate) {
    queryParams.push(params.data.startDate);
    whereClauses.push(`ci.absence_date >= $${queryParams.length}`);
  }
  if (params.success && params.data.endDate) {
    queryParams.push(params.data.endDate);
    whereClauses.push(`ci.absence_date <= $${queryParams.length}`);
  }

  const q = `
    SELECT
      ci.id AS instance_id,
      ci.schedule_block_id,
      ci.absence_date,
      ci.absence_id,
      ci.substitute_staff_id,
      ci.is_covered,
      sub.first_name AS sub_staff_first,
      sub.last_name AS sub_staff_last,
      sb.day_of_week,
      sb.start_time,
      sb.end_time,
      sb.student_id,
      sb.location,
      stu.first_name AS student_first,
      stu.last_name AS student_last,
      st.name AS service_type_name,
      ci.original_staff_id,
      orig.first_name AS original_staff_first,
      orig.last_name AS original_staff_last
    FROM coverage_instances ci
    JOIN schedule_blocks sb ON sb.id = ci.schedule_block_id
    LEFT JOIN students stu ON stu.id = sb.student_id
    LEFT JOIN service_types st ON st.id = sb.service_type_id
    LEFT JOIN staff orig ON orig.id = ci.original_staff_id
    LEFT JOIN staff sub ON sub.id = ci.substitute_staff_id
    WHERE ${whereClauses.join(" AND ")}
    ORDER BY ci.absence_date ASC, sb.start_time ASC
  `;

  const result = await pool.query(q, queryParams);
  res.json(result.rows.map((b: any) => ({
    instanceId: b.instance_id,
    id: b.schedule_block_id,
    absenceDate: b.absence_date ?? null,
    dayOfWeek: b.day_of_week,
    startTime: b.start_time,
    endTime: b.end_time,
    studentId: b.student_id,
    studentName: b.student_first ? `${b.student_first} ${b.student_last}` : null,
    serviceTypeName: b.service_type_name ?? null,
    originalStaffId: b.original_staff_id,
    originalStaffName: b.original_staff_first ? `${b.original_staff_first} ${b.original_staff_last}` : null,
    substituteStaffId: b.substitute_staff_id ?? null,
    substituteStaffName: b.sub_staff_first ? `${b.sub_staff_first} ${b.sub_staff_last}` : null,
    absenceId: b.absence_id ?? null,
    isCovered: b.is_covered,
    location: b.location ?? null,
  })));
});

/**
 * Assign substitute to a coverage instance (not the schedule template).
 * Requires absenceDate in the request body to identify the correct instance.
 */
router.post("/schedule-blocks/:id/assign-substitute", requireAdmin, async (req, res): Promise<void> => {
  const params = AssignSubstituteParams.safeParse(req.params);
  if (!params.success) { res.status(400).json({ error: "Invalid id" }); return; }
  const parsed = AssignSubstituteBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.message }); return; }

  const [sub] = await db.select({ id: staffTable.id, firstName: staffTable.firstName, lastName: staffTable.lastName })
    .from(staffTable).where(eq(staffTable.id, parsed.data.substituteStaffId));
  if (!sub) { res.status(404).json({ error: "Substitute staff not found" }); return; }

  // Locate the coverage instance for this block + date
  const conditions: any[] = [eq(coverageInstancesTable.scheduleBlockId, params.data.id)];
  if (parsed.data.absenceDate) {
    conditions.push(eq(coverageInstancesTable.absenceDate, parsed.data.absenceDate));
  }

  const [instance] = await db
    .update(coverageInstancesTable)
    .set({ substituteStaffId: parsed.data.substituteStaffId, isCovered: true })
    .where(and(...conditions))
    .returning();

  if (!instance) { res.status(404).json({ error: "Coverage instance not found for this block and date" }); return; }

  res.json({
    instanceId: instance.id,
    scheduleBlockId: instance.scheduleBlockId,
    absenceDate: instance.absenceDate,
    substituteStaffId: sub.id,
    substituteStaffName: `${sub.firstName} ${sub.lastName}`,
    isCovered: true,
    message: `${sub.firstName} ${sub.lastName} assigned as substitute`,
  });
});

export default router;
