// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/themes/ForestAndCloud.tsx": () => import("../components/mockups/themes/ForestAndCloud.tsx"),
  "./components/mockups/themes/InkAir.tsx": () => import("../components/mockups/themes/InkAir.tsx"),
  "./components/mockups/themes/MidnightMoss.tsx": () => import("../components/mockups/themes/MidnightMoss.tsx"),
  "./components/mockups/themes/OpenAir.tsx": () => import("../components/mockups/themes/OpenAir.tsx"),
  "./components/mockups/themes/SlateAndSprout.tsx": () => import("../components/mockups/themes/SlateAndSprout.tsx"),
  "./components/mockups/themes/WarmStone.tsx": () => import("../components/mockups/themes/WarmStone.tsx"),
  "./components/mockups/trellis-redesign/GlassTerminal.tsx": () => import("../components/mockups/trellis-redesign/GlassTerminal.tsx"),
  "./components/mockups/trellis-redesign/InkAndAir.tsx": () => import("../components/mockups/trellis-redesign/InkAndAir.tsx"),
  "./components/mockups/trellis-redesign/MonochromeGrid.tsx": () => import("../components/mockups/trellis-redesign/MonochromeGrid.tsx"),
  "./components/mockups/trellis-redesign/SwissPrecision.tsx": () => import("../components/mockups/trellis-redesign/SwissPrecision.tsx"),
  "./components/mockups/directions/D1PrecisionCommand.tsx": () => import("../components/mockups/directions/D1PrecisionCommand.tsx"),
  "./components/mockups/directions/D2WarmEduTrust.tsx": () => import("../components/mockups/directions/D2WarmEduTrust.tsx"),
  "./components/mockups/directions/D3ModernSaas.tsx": () => import("../components/mockups/directions/D3ModernSaas.tsx"),
  "./components/mockups/directions/D4ComplianceAuthority.tsx": () => import("../components/mockups/directions/D4ComplianceAuthority.tsx"),
  "./components/mockups/directions/D5FutureGlass.tsx": () => import("../components/mockups/directions/D5FutureGlass.tsx")
};
