// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trellis-redesign/GlassTerminal.tsx": () => import("../components/mockups/trellis-redesign/GlassTerminal.tsx"),
  "./components/mockups/trellis-redesign/InkAndAir.tsx": () => import("../components/mockups/trellis-redesign/InkAndAir.tsx"),
  "./components/mockups/trellis-redesign/MonochromeGrid.tsx": () => import("../components/mockups/trellis-redesign/MonochromeGrid.tsx"),
  "./components/mockups/trellis-redesign/SwissPrecision.tsx": () => import("../components/mockups/trellis-redesign/SwissPrecision.tsx")
};
