import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  scheduleBlocksTable, staffTable, studentsTable, serviceTypesTable,
  serviceRequirementsTable,
} from "@workspace/db";
import {
  ListScheduleBlocksQueryParams,
  CreateScheduleBlockBody,
  UpdateScheduleBlockParams,
  UpdateScheduleBlockBody,
  DeleteScheduleBlockParams,
} from "@workspace/api-zod";
import { eq, and, or, sql, isNull, lte, gte } from "drizzle-orm";
import { getEnforcedDistrictId } from "../../middlewares/auth";
import type { AuthedRequest } from "../../middlewares/auth";
import { assertScheduleBlockInCallerDistrict } from "../../lib/districtScope";
import { getActiveSchoolYearIdForStudent } from "../../lib/activeSchoolYear";
import { resolveActiveYearId, blockToJson } from "./shared";
import { isBlockActiveOnDate } from "../../lib/scheduleUtils";

const DAY_INDEX: Record<string, number> = {
  monday: 0, tuesday: 1, wednesday: 2, thursday: 3,
  friday: 4, saturday: 5, sunday: 6,
};

const router: IRouter = Router();

router.get("/schedule-blocks", async (req, res): Promise<void> => {
  const params = ListScheduleBlocksQueryParams.safeParse(req.query);
  const conditions: any[] = [isNull(scheduleBlocksTable.deletedAt)];
  if (params.success) {
    if (params.data.staffId) conditions.push(eq(scheduleBlocksTable.staffId, Number(params.data.staffId)));
    if (params.data.studentId) conditions.push(eq(scheduleBlocksTable.studentId, Number(params.data.studentId)));
    if (params.data.dayOfWeek) conditions.push(eq(scheduleBlocksTable.dayOfWeek, params.data.dayOfWeek));
    if (params.data.weekOf) {
      // weekOf semantics: "blocks active during the week starting weekOf".
      // Match either a one-off block tagged with that exact weekOf, OR a recurring
      // block whose effective_from/to range covers that week. Biweekly off-week
      // recurring blocks are filtered out post-query via isBlockActiveOnDate.
      const weekStart = params.data.weekOf;
      if (!/^\d{4}-\d{2}-\d{2}$/.test(weekStart)) {
        res.status(400).json({ error: "weekOf must be YYYY-MM-DD" });
        return;
      }
      const weekEndDate = new Date(`${weekStart}T00:00:00Z`);
      if (Number.isNaN(weekEndDate.getTime())) {
        res.status(400).json({ error: "weekOf is not a valid date" });
        return;
      }
      weekEndDate.setUTCDate(weekEndDate.getUTCDate() + 6);
      const weekEnd = weekEndDate.toISOString().substring(0, 10);
      conditions.push(
        or(
          eq(scheduleBlocksTable.weekOf, weekStart),
          and(
            eq(scheduleBlocksTable.isRecurring, true),
            or(isNull(scheduleBlocksTable.effectiveFrom), lte(scheduleBlocksTable.effectiveFrom, weekEnd)),
            or(isNull(scheduleBlocksTable.effectiveTo), gte(scheduleBlocksTable.effectiveTo, weekStart)),
          ),
        )!,
      );
    }
  }
  if (params.success && params.data.schoolId) conditions.push(sql`${scheduleBlocksTable.staffId} IN (SELECT id FROM staff WHERE school_id = ${Number(params.data.schoolId)})`);
  {
    const enforcedDid = getEnforcedDistrictId(req as unknown as AuthedRequest);
    if (enforcedDid !== null) {
      conditions.push(sql`${scheduleBlocksTable.staffId} IN (SELECT id FROM staff WHERE school_id IN (SELECT id FROM schools WHERE district_id = ${enforcedDid}))`);
    } else if (params.success && params.data.districtId) {
      conditions.push(sql`${scheduleBlocksTable.staffId} IN (SELECT id FROM staff WHERE school_id IN (SELECT id FROM schools WHERE district_id = ${Number(params.data.districtId)}))`);
    }
  }

  const explicitYearId = params.success ? (params.data.schoolYearId ?? null) : null;
  const enforcedDidForYear = getEnforcedDistrictId(req as unknown as AuthedRequest);
  const activeYearId = explicitYearId ?? await resolveActiveYearId(req, enforcedDidForYear !== null ? enforcedDidForYear : (params.success ? (params.data.districtId ?? null) : null));
  if (activeYearId != null) {
    conditions.push(eq(scheduleBlocksTable.schoolYearId, activeYearId));
  }

  const blocks = await db
    .select({
      id: scheduleBlocksTable.id,
      staffId: scheduleBlocksTable.staffId,
      studentId: scheduleBlocksTable.studentId,
      serviceTypeId: scheduleBlocksTable.serviceTypeId,
      dayOfWeek: scheduleBlocksTable.dayOfWeek,
      startTime: scheduleBlocksTable.startTime,
      endTime: scheduleBlocksTable.endTime,
      location: scheduleBlocksTable.location,
      blockLabel: scheduleBlocksTable.blockLabel,
      blockType: scheduleBlocksTable.blockType,
      notes: scheduleBlocksTable.notes,
      isRecurring: scheduleBlocksTable.isRecurring,
      recurrenceType: scheduleBlocksTable.recurrenceType,
      effectiveFrom: scheduleBlocksTable.effectiveFrom,
      effectiveTo: scheduleBlocksTable.effectiveTo,
      weekOf: scheduleBlocksTable.weekOf,
      isAutoGenerated: scheduleBlocksTable.isAutoGenerated,
      rotationDay: scheduleBlocksTable.rotationDay,
      createdAt: scheduleBlocksTable.createdAt,
      staffFirst: staffTable.firstName,
      staffLast: staffTable.lastName,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
      serviceTypeName: serviceTypesTable.name,
    })
    .from(scheduleBlocksTable)
    .leftJoin(staffTable, eq(staffTable.id, scheduleBlocksTable.staffId))
    .leftJoin(studentsTable, eq(studentsTable.id, scheduleBlocksTable.studentId))
    .leftJoin(serviceTypesTable, eq(serviceTypesTable.id, scheduleBlocksTable.serviceTypeId))
    .where(conditions.length > 0 ? and(...conditions) : undefined);

  // When weekOf is supplied this endpoint becomes a date-targeted enumeration
  // for that week, so we must hide biweekly recurring blocks falling on their
  // off-week. Weekly (or null/non-biweekly) blocks short-circuit to true in
  // isBlockActiveOnDate and are unaffected.
  const filteredBlocks = (params.success && params.data.weekOf)
    ? blocks.filter(b => {
        if (!b.isRecurring) return true;
        const dayIdx = DAY_INDEX[b.dayOfWeek] ?? 0;
        const target = new Date(`${params.data.weekOf}T12:00:00`);
        target.setDate(target.getDate() + dayIdx);
        return isBlockActiveOnDate(
          {
            id: b.id,
            isRecurring: b.isRecurring,
            recurrenceType: b.recurrenceType ?? "weekly",
            effectiveFrom: b.effectiveFrom ?? null,
          },
          target,
        );
      })
    : blocks;

  res.json(filteredBlocks.map(b => blockToJson(b,
    b.staffFirst ? `${b.staffFirst} ${b.staffLast}` : null,
    b.studentFirst ? `${b.studentFirst} ${b.studentLast}` : null,
    b.serviceTypeName
  )));
});

router.post("/schedule-blocks", async (req, res): Promise<void> => {
  const parsed = CreateScheduleBlockBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const schoolYearId = parsed.data.studentId
    ? await getActiveSchoolYearIdForStudent(parsed.data.studentId)
    : null;
  // recurrenceType is NOT NULL with a default in the DB; drop nulls so the
  // default ("weekly") applies rather than failing the insert type check.
  const { recurrenceType, ...rest } = parsed.data;
  const [block] = await db.insert(scheduleBlocksTable).values({
    ...rest,
    ...(recurrenceType != null ? { recurrenceType } : {}),
    isAutoGenerated: false,
    ...(schoolYearId != null ? { schoolYearId } : {}),
  }).returning();
  res.status(201).json(blockToJson(block));
});

router.patch("/schedule-blocks/:id", async (req, res): Promise<void> => {
  const params = UpdateScheduleBlockParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }
  if (!(await assertScheduleBlockInCallerDistrict(req as unknown as AuthedRequest, params.data.id, res))) return;
  const parsed = UpdateScheduleBlockBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const updateData: Partial<typeof scheduleBlocksTable.$inferInsert> = {};
  if (parsed.data.studentId !== undefined) updateData.studentId = parsed.data.studentId;
  if (parsed.data.dayOfWeek != null) updateData.dayOfWeek = parsed.data.dayOfWeek;
  if (parsed.data.startTime != null) updateData.startTime = parsed.data.startTime;
  if (parsed.data.endTime != null) updateData.endTime = parsed.data.endTime;
  if (parsed.data.location !== undefined) updateData.location = parsed.data.location;
  if (parsed.data.blockLabel !== undefined) updateData.blockLabel = parsed.data.blockLabel;
  if (parsed.data.notes !== undefined) updateData.notes = parsed.data.notes;
  if (parsed.data.recurrenceType != null) updateData.recurrenceType = parsed.data.recurrenceType;
  if (parsed.data.effectiveFrom !== undefined) updateData.effectiveFrom = parsed.data.effectiveFrom ?? null;
  if (parsed.data.effectiveTo !== undefined) updateData.effectiveTo = parsed.data.effectiveTo ?? null;

  const [block] = await db.update(scheduleBlocksTable).set(updateData).where(eq(scheduleBlocksTable.id, params.data.id)).returning();
  if (!block) {
    res.status(404).json({ error: "Block not found" });
    return;
  }
  res.json(blockToJson(block));
});

router.delete("/schedule-blocks/:id", async (req, res): Promise<void> => {
  const params = DeleteScheduleBlockParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }
  if (!(await assertScheduleBlockInCallerDistrict(req as unknown as AuthedRequest, params.data.id, res))) return;
  await db.update(scheduleBlocksTable).set({ deletedAt: new Date() }).where(eq(scheduleBlocksTable.id, params.data.id));
  res.sendStatus(204);
});

router.get("/schedule-blocks/conflicts", async (req, res): Promise<void> => {
  const conflictYearId = await resolveActiveYearId(req, null);
  const conflictConditions: any[] = [eq(scheduleBlocksTable.isRecurring, true), isNull(scheduleBlocksTable.deletedAt)];
  if (conflictYearId != null) conflictConditions.push(eq(scheduleBlocksTable.schoolYearId, conflictYearId));

  const allBlocks = await db
    .select({
      id: scheduleBlocksTable.id,
      staffId: scheduleBlocksTable.staffId,
      dayOfWeek: scheduleBlocksTable.dayOfWeek,
      startTime: scheduleBlocksTable.startTime,
      endTime: scheduleBlocksTable.endTime,
      studentId: scheduleBlocksTable.studentId,
      staffFirst: staffTable.firstName,
      staffLast: staffTable.lastName,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
    })
    .from(scheduleBlocksTable)
    .leftJoin(staffTable, eq(staffTable.id, scheduleBlocksTable.staffId))
    .leftJoin(studentsTable, eq(studentsTable.id, scheduleBlocksTable.studentId))
    .where(and(...conflictConditions));

  const grouped = new Map<string, typeof allBlocks>();
  for (const b of allBlocks) {
    const key = `${b.staffId}-${b.dayOfWeek}`;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(b);
  }

  const conflicts = [];
  for (const [_, blocks] of grouped.entries()) {
    if (blocks.length < 2) continue;
    const conflictingPairs: any[] = [];
    for (let i = 0; i < blocks.length; i++) {
      for (let j = i + 1; j < blocks.length; j++) {
        const a = blocks[i];
        const b = blocks[j];
        if (a.startTime < b.endTime && b.startTime < a.endTime) {
          const overlapStart = a.startTime > b.startTime ? a.startTime : b.startTime;
          const overlapEnd = a.endTime < b.endTime ? a.endTime : b.endTime;
          const [osH, osM] = overlapStart.split(":").map(Number);
          const [oeH, oeM] = overlapEnd.split(":").map(Number);
          const overlapMinutes = (oeH * 60 + oeM) - (osH * 60 + osM);

          conflictingPairs.push({
            staffId: a.staffId,
            staffName: a.staffFirst ? `${a.staffFirst} ${a.staffLast}` : `Staff ${a.staffId}`,
            dayOfWeek: a.dayOfWeek,
            conflictingBlocks: [
              { id: a.id, startTime: a.startTime, endTime: a.endTime, studentName: a.studentFirst ? `${a.studentFirst} ${a.studentLast}` : null },
              { id: b.id, startTime: b.startTime, endTime: b.endTime, studentName: b.studentFirst ? `${b.studentFirst} ${b.studentLast}` : null },
            ],
            overlapMinutes,
          });
        }
      }
    }
    conflicts.push(...conflictingPairs);
  }

  res.json(conflicts);
});

router.get("/schedule-blocks/coverage-gaps", async (req, res): Promise<void> => {
  const gapYearId = await resolveActiveYearId(req, null);
  const coveredConditions: any[] = [eq(scheduleBlocksTable.isRecurring, true), isNull(scheduleBlocksTable.deletedAt)];
  if (gapYearId != null) coveredConditions.push(eq(scheduleBlocksTable.schoolYearId, gapYearId));

  const reqs = await db
    .select({
      id: serviceRequirementsTable.id,
      studentId: serviceRequirementsTable.studentId,
      serviceTypeId: serviceRequirementsTable.serviceTypeId,
      requiredMinutes: serviceRequirementsTable.requiredMinutes,
      intervalType: serviceRequirementsTable.intervalType,
      studentFirst: studentsTable.firstName,
      studentLast: studentsTable.lastName,
      serviceTypeName: serviceTypesTable.name,
    })
    .from(serviceRequirementsTable)
    .leftJoin(studentsTable, eq(studentsTable.id, serviceRequirementsTable.studentId))
    .leftJoin(serviceTypesTable, eq(serviceTypesTable.id, serviceRequirementsTable.serviceTypeId))
    .where(eq(serviceRequirementsTable.active, true));

  const coveredPairs = await db
    .selectDistinct({
      studentId: scheduleBlocksTable.studentId,
      serviceTypeId: scheduleBlocksTable.serviceTypeId,
    })
    .from(scheduleBlocksTable)
    .where(and(...coveredConditions));

  const coveredSet = new Set(coveredPairs.map(p => `${p.studentId}-${p.serviceTypeId}`));

  const gaps = reqs
    .filter(req => !coveredSet.has(`${req.studentId}-${req.serviceTypeId}`))
    .map(req => ({
      studentId: req.studentId,
      studentName: req.studentFirst ? `${req.studentFirst} ${req.studentLast}` : `Student ${req.studentId}`,
      serviceRequirementId: req.id,
      serviceTypeName: req.serviceTypeName ?? "Unknown",
      gapDescription: `No scheduled blocks found for ${req.serviceTypeName ?? "this service"} (${req.requiredMinutes} min/${req.intervalType} required)`,
      severity: req.requiredMinutes > 60 ? "high" : "medium",
    }));

  res.json(gaps);
});

export default router;
