import type { Request } from "express";
import { getActiveSchoolYearId } from "../../lib/activeSchoolYear";
import { getPublicMeta } from "../../lib/clerkClaims";
import { requireRoles } from "../../middlewares/auth";

export const requireAdmin = requireRoles("admin", "coordinator");

export async function resolveActiveYearId(req: Request, districtIdHint?: number | null): Promise<number | null> {
  const did = districtIdHint ?? getPublicMeta(req).districtId;
  if (did) return getActiveSchoolYearId(did);
  if (process.env.NODE_ENV !== "production") {
    const { pool } = await import("@workspace/db");
    const result = await pool.query<{ id: number }>("SELECT id FROM school_years WHERE is_active = true ORDER BY id LIMIT 1");
    return result.rows[0]?.id ?? null;
  }
  return null;
}

export function blockToJson(b: any, staffName?: string | null, studentName?: string | null, serviceTypeName?: string | null) {
  return {
    id: b.id,
    staffId: b.staffId,
    staffName: staffName ?? null,
    studentId: b.studentId,
    studentName: studentName ?? null,
    serviceTypeId: b.serviceTypeId,
    serviceTypeName: serviceTypeName ?? null,
    dayOfWeek: b.dayOfWeek,
    startTime: b.startTime,
    endTime: b.endTime,
    location: b.location,
    blockLabel: b.blockLabel,
    blockType: b.blockType,
    notes: b.notes,
    isRecurring: b.isRecurring,
    recurrenceType: b.recurrenceType ?? "weekly",
    effectiveFrom: b.effectiveFrom ?? null,
    effectiveTo: b.effectiveTo ?? null,
    weekOf: b.weekOf,
    isAutoGenerated: b.isAutoGenerated,
    rotationDay: b.rotationDay ?? null,
    createdAt: b.createdAt instanceof Date ? b.createdAt.toISOString() : b.createdAt,
  };
}
