import { pgTable, text, serial, timestamp, integer, boolean, date, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { staffTable } from "./staff";
import { studentsTable } from "./students";
import { serviceTypesTable } from "./serviceTypes";
import { schoolYearsTable } from "./schoolYears";

export const scheduleBlocksTable = pgTable("schedule_blocks", {
  id: serial("id").primaryKey(),
  staffId: integer("staff_id").notNull().references(() => staffTable.id),
  studentId: integer("student_id").references(() => studentsTable.id),
  serviceTypeId: integer("service_type_id").references(() => serviceTypesTable.id),
  // For standard schedules: "monday"–"friday"
  // For rotating schedules: still store the calendar day for display; rotationDay is the logical slot
  dayOfWeek: text("day_of_week").notNull(),
  startTime: text("start_time").notNull(),
  endTime: text("end_time").notNull(),
  location: text("location"),
  blockLabel: text("block_label"),
  blockType: text("block_type").notNull().default("service"),
  notes: text("notes"),
  isRecurring: boolean("is_recurring").notNull().default(true),
  // "weekly" | "biweekly" — only relevant when isRecurring = true
  recurrenceType: text("recurrence_type").notNull().default("weekly"),
  effectiveFrom: date("effective_from"),
  effectiveTo: date("effective_to"),
  weekOf: text("week_of"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  rotationDay: text("rotation_day"),
  schoolYearId: integer("school_year_id").references(() => schoolYearsTable.id),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => [
  index("sb_staff_day_idx").on(table.staffId, table.dayOfWeek),
  index("sb_recurring_staff_idx").on(table.isRecurring, table.staffId),
  index("sb_student_idx").on(table.studentId),
]);

export const insertScheduleBlockSchema = createInsertSchema(scheduleBlocksTable).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true });
export type InsertScheduleBlock = z.infer<typeof insertScheduleBlockSchema>;
export type ScheduleBlock = typeof scheduleBlocksTable.$inferSelect;
