import { pgTable, text, serial, timestamp, integer, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { staffTable } from "./staff";
import { studentsTable } from "./students";
import { serviceTypesTable } from "./serviceTypes";

export const scheduleBlocksTable = pgTable("schedule_blocks", {
  id: serial("id").primaryKey(),
  staffId: integer("staff_id").notNull().references(() => staffTable.id),
  studentId: integer("student_id").references(() => studentsTable.id),
  serviceTypeId: integer("service_type_id").references(() => serviceTypesTable.id),
  dayOfWeek: text("day_of_week").notNull(), // monday | tuesday | wednesday | thursday | friday
  startTime: text("start_time").notNull(), // HH:MM
  endTime: text("end_time").notNull(), // HH:MM
  location: text("location"),
  blockLabel: text("block_label"), // Block 1 | Block 2 | Lunch | Transition | etc.
  blockType: text("block_type").notNull().default("service"), // service | para_support | preparation | meeting | unavailable
  notes: text("notes"),
  isRecurring: boolean("is_recurring").notNull().default(true),
  weekOf: text("week_of"), // ISO date of Monday of target week, for non-recurring
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertScheduleBlockSchema = createInsertSchema(scheduleBlocksTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertScheduleBlock = z.infer<typeof insertScheduleBlockSchema>;
export type ScheduleBlock = typeof scheduleBlocksTable.$inferSelect;
